spring.application.name=deploy6
server.port=9091

# === KONFIGURASI DATABASE MYSQL ===
# Ganti 'db_kampus' dengan nama database yang akan kamu buat
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/db_deploy?serverTimezone=Asia/Jakarta
# Default username XAMPP biasanya 'root'
spring.datasource.username=root
# Default password XAMPP biasanya kosong (biarkan kosong jika tidak pakai password)
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# === KONFIGURASI JPA / HIBERNATE ===
# 'update' berarti Spring Boot akan otomatis membuatkan/mengupdate tabel di database
spring.jpa.hibernate.ddl-auto=update
# Untuk melihat proses SQL di terminal/console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect